{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-applovin",
    "version": "9.15.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hyh4ijiwtvhgdneaukok7no2he"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "applovin",
          "version": {
            "requires": "9.15.3.a24"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "applovin",
          "version": {
            "requires": "9.15.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-applovin-9.15.3.1.aar",
          "url": "hera-applovin-9.15.3.1.aar",
          "size": 24621,
          "sha512": "4f03af4dec15c51e6652a8870f65f31d9024a45e13c35d7935f4e250381acdb514bcc03b39af30f7ab8055c2eb6f62468906af124964c158bc441901ad10aba9",
          "sha256": "540b924a0b88500ca5c0890d1e5cae067587cdfa06a2b5021d6c9e7e569408f8",
          "sha1": "31b9adc77535f670104a36f2f15df6ad3cd2e147",
          "md5": "16f852bffec8c00e43b2ffd8f49f63ec"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "applovin",
          "version": {
            "requires": "9.15.3.a24"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "applovin",
          "version": {
            "requires": "9.15.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-applovin-9.15.3.1.aar",
          "url": "hera-applovin-9.15.3.1.aar",
          "size": 24621,
          "sha512": "4f03af4dec15c51e6652a8870f65f31d9024a45e13c35d7935f4e250381acdb514bcc03b39af30f7ab8055c2eb6f62468906af124964c158bc441901ad10aba9",
          "sha256": "540b924a0b88500ca5c0890d1e5cae067587cdfa06a2b5021d6c9e7e569408f8",
          "sha1": "31b9adc77535f670104a36f2f15df6ad3cd2e147",
          "md5": "16f852bffec8c00e43b2ffd8f49f63ec"
        }
      ]
    }
  ]
}
