{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-applovin",
    "version": "9.15.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "eob2na2ufzc53g2ihxcogrxauy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "applovin",
          "version": {
            "requires": "9.15.3.a24"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "applovin",
          "version": {
            "requires": "9.15.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-applovin-9.15.3.0.aar",
          "url": "hera-applovin-9.15.3.0.aar",
          "size": 24620,
          "sha512": "b40849e9602a6bd6b803b1ce39875281d9e9c490d5bc92fecca85046fcd9b6019bba21dcfbd849abeff31000e793a529c7818238cce21bd51a6cf6b3635d7b01",
          "sha256": "0789df0f0365e977eefdcf84b0c9ada5c34b059023bc09c8e930580b6a4615c9",
          "sha1": "ce3f8772475425c40f0a6b623505185a73a2053e",
          "md5": "94f007548edb713cdeb47c36f4052b6f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "applovin",
          "version": {
            "requires": "9.15.3.a24"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "applovin",
          "version": {
            "requires": "9.15.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-applovin-9.15.3.0.aar",
          "url": "hera-applovin-9.15.3.0.aar",
          "size": 24620,
          "sha512": "b40849e9602a6bd6b803b1ce39875281d9e9c490d5bc92fecca85046fcd9b6019bba21dcfbd849abeff31000e793a529c7818238cce21bd51a6cf6b3635d7b01",
          "sha256": "0789df0f0365e977eefdcf84b0c9ada5c34b059023bc09c8e930580b6a4615c9",
          "sha1": "ce3f8772475425c40f0a6b623505185a73a2053e",
          "md5": "94f007548edb713cdeb47c36f4052b6f"
        }
      ]
    }
  ]
}
