{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-tiktok",
    "version": "3.8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpyj65xjevfb3ppdsb2bgvg6ii"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "tiktok",
          "version": {
            "requires": "3.8.0.2.a25"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "pangle",
          "version": {
            "requires": "3.8.1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "hera-tiktok-3.8.0.0.aar",
          "url": "hera-tiktok-3.8.0.0.aar",
          "size": 22383,
          "sha512": "eaab3eff8933c6139c195d5d764b65e9321ed3a44587b04ed6768a30c2b53f0eaf9fc30721860eb0a4fbb434421fb6fd7d68c1c6ad209f416f279a5bf617caa3",
          "sha256": "dc7d1fd29e80f2d7a379c171ce0be66d7af0ebaa298d31fbeebba217b6850cf3",
          "sha1": "ae00ae9f06cda27bc24f1f52f2b4946fbd54b74d",
          "md5": "ef353f6349ae79c3ee0c61b457692b7a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "tiktok",
          "version": {
            "requires": "3.8.0.2.a25"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "pangle",
          "version": {
            "requires": "3.8.1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "hera-tiktok-3.8.0.0.aar",
          "url": "hera-tiktok-3.8.0.0.aar",
          "size": 22383,
          "sha512": "eaab3eff8933c6139c195d5d764b65e9321ed3a44587b04ed6768a30c2b53f0eaf9fc30721860eb0a4fbb434421fb6fd7d68c1c6ad209f416f279a5bf617caa3",
          "sha256": "dc7d1fd29e80f2d7a379c171ce0be66d7af0ebaa298d31fbeebba217b6850cf3",
          "sha1": "ae00ae9f06cda27bc24f1f52f2b4946fbd54b74d",
          "md5": "ef353f6349ae79c3ee0c61b457692b7a"
        }
      ]
    }
  ]
}
