{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-applovin",
    "version": "10.2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vqv4bg6xozeu5oflz5aopkgtbm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "applovin",
          "version": {
            "requires": "10.2.0.a25"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "applovin",
          "version": {
            "requires": "10.2.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-applovin-10.2.0.0.aar",
          "url": "hera-applovin-10.2.0.0.aar",
          "size": 24536,
          "sha512": "d5b864db83510614102b5236b9c58bc1149182627d5eb3e142a87ef9ee974f6e0f519221b956db5330548ee8fc46f4fb8332ea678629a0eaf01c06f680a20ca3",
          "sha256": "3c1e4c55f970bfe786a4c562e44d3878e93b37f6c39623216eb5605c7c758a7c",
          "sha1": "a8cd6247f3a15ea8b91f25180b0194af09bd4ddc",
          "md5": "a00fd185a8a2a4d62c965bc1a0119cb6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "applovin",
          "version": {
            "requires": "10.2.0.a25"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "applovin",
          "version": {
            "requires": "10.2.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-applovin-10.2.0.0.aar",
          "url": "hera-applovin-10.2.0.0.aar",
          "size": 24536,
          "sha512": "d5b864db83510614102b5236b9c58bc1149182627d5eb3e142a87ef9ee974f6e0f519221b956db5330548ee8fc46f4fb8332ea678629a0eaf01c06f680a20ca3",
          "sha256": "3c1e4c55f970bfe786a4c562e44d3878e93b37f6c39623216eb5605c7c758a7c",
          "sha1": "a8cd6247f3a15ea8b91f25180b0194af09bd4ddc",
          "md5": "a00fd185a8a2a4d62c965bc1a0119cb6"
        }
      ]
    }
  ]
}
