{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-applovin",
    "version": "9.15.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "zvlhp77fvrgcth7s3fuutnff6q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "applovin",
          "version": {
            "requires": "9.15.0.a23"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "applovin",
          "version": {
            "requires": "9.15.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-applovin-9.15.0.1.aar",
          "url": "hera-applovin-9.15.0.1.aar",
          "size": 24315,
          "sha512": "4d756a2cd72e57681ef1cd2c059dc5f845b12ff93159ea589fc890dadc3a7c9a7e1091714d79cb514aacd24754b0db5731440e6ffdd09735fe7febf7b1dbd930",
          "sha256": "5288f2bd2b8b6d89e054508d059f97cc55a084b0a62c534be301c0a029a65593",
          "sha1": "612acd33c082c3d80e9c06d7fa82737fc3004d47",
          "md5": "006059743852a8d0179c713f63cc36f9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "applovin",
          "version": {
            "requires": "9.15.0.a23"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "applovin",
          "version": {
            "requires": "9.15.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-applovin-9.15.0.1.aar",
          "url": "hera-applovin-9.15.0.1.aar",
          "size": 24315,
          "sha512": "4d756a2cd72e57681ef1cd2c059dc5f845b12ff93159ea589fc890dadc3a7c9a7e1091714d79cb514aacd24754b0db5731440e6ffdd09735fe7febf7b1dbd930",
          "sha256": "5288f2bd2b8b6d89e054508d059f97cc55a084b0a62c534be301c0a029a65593",
          "sha1": "612acd33c082c3d80e9c06d7fa82737fc3004d47",
          "md5": "006059743852a8d0179c713f63cc36f9"
        }
      ]
    }
  ]
}
