{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tabtk55qqjdb7k5cwryh3kdh34"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "amr",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admost",
          "version": {
            "requires": "0.2.4.a25"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admob-gt-17.2.0-adapter",
          "version": {
            "requires": "1.0.6.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "facebook",
          "version": {
            "requires": "6.4.0.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "s2sbidding-adapter",
          "version": {
            "requires": "1.0.1.a25"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "hera-1.1.3.aar",
          "url": "hera-1.1.3.aar",
          "size": 126422,
          "sha512": "414c8c3a6a2ee8980f33f476fb728823c0092317e8d509232964847fe9e872c2ebed5f60b9713031b97071d0b924226550875db98786147094261d8a4b56fea7",
          "sha256": "24c31af292dd3e8b44f7b6fe1fa8c51cb5edd004ddbf0e49a2885e64692f1daa",
          "sha1": "451b63492c9f42006f50a17c47fe89f732481af8",
          "md5": "474056b891d52e6c12259c46ea8c955a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "amr",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admost",
          "version": {
            "requires": "0.2.4.a25"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admob-gt-17.2.0-adapter",
          "version": {
            "requires": "1.0.6.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "facebook",
          "version": {
            "requires": "6.4.0.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "s2sbidding-adapter",
          "version": {
            "requires": "1.0.1.a25"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.mopub",
          "module": "mopub-sdk",
          "version": {
            "requires": "5.15.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mopub-sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "admob",
          "version": {
            "requires": "19.6.0.1"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "facebookaudiencenetwork",
          "version": {
            "requires": "6.3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-1.1.3.aar",
          "url": "hera-1.1.3.aar",
          "size": 126422,
          "sha512": "414c8c3a6a2ee8980f33f476fb728823c0092317e8d509232964847fe9e872c2ebed5f60b9713031b97071d0b924226550875db98786147094261d8a4b56fea7",
          "sha256": "24c31af292dd3e8b44f7b6fe1fa8c51cb5edd004ddbf0e49a2885e64692f1daa",
          "sha1": "451b63492c9f42006f50a17c47fe89f732481af8",
          "md5": "474056b891d52e6c12259c46ea8c955a"
        }
      ]
    }
  ]
}
