{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "sv2fum4h65hvnkyv7yjfdbsgmi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "amr",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admost",
          "version": {
            "requires": "0.2.4.a24"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admob-gt-17.2.0-adapter",
          "version": {
            "requires": "1.0.6.a24"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "facebook",
          "version": {
            "requires": "6.3.0.a24"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "s2sbidding-adapter",
          "version": {
            "requires": "1.0.1.a24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-1.0.4.aar",
          "url": "hera-1.0.4.aar",
          "size": 133675,
          "sha512": "8377cef6976317bc0cd9b199369e162f67f54fad83a1b59995e8121f5728c9cddc60c9f81aacec0c1a12ac143e47624c8bf4d6d3af8e177892b41a4bc0d637df",
          "sha256": "8840b3a1c124a6be889edefafab83474ebb3d24c35d13882b3b3b09b53edfa8a",
          "sha1": "db81e81cacee687426a0f4509821d55ba1425a1b",
          "md5": "8ed2d363b66b3f0ed64c657f2a5f4db2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "amr",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admost",
          "version": {
            "requires": "0.2.4.a24"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admob-gt-17.2.0-adapter",
          "version": {
            "requires": "1.0.6.a24"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "facebook",
          "version": {
            "requires": "6.3.0.a24"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "s2sbidding-adapter",
          "version": {
            "requires": "1.0.1.a24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.mopub",
          "module": "mopub-sdk",
          "version": {
            "requires": "5.15.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mopub-sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "admob",
          "version": {
            "requires": "19.6.0.1"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "facebookaudiencenetwork",
          "version": {
            "requires": "6.3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-1.0.4.aar",
          "url": "hera-1.0.4.aar",
          "size": 133675,
          "sha512": "8377cef6976317bc0cd9b199369e162f67f54fad83a1b59995e8121f5728c9cddc60c9f81aacec0c1a12ac143e47624c8bf4d6d3af8e177892b41a4bc0d637df",
          "sha256": "8840b3a1c124a6be889edefafab83474ebb3d24c35d13882b3b3b09b53edfa8a",
          "sha1": "db81e81cacee687426a0f4509821d55ba1425a1b",
          "md5": "8ed2d363b66b3f0ed64c657f2a5f4db2"
        }
      ]
    }
  ]
}
