{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-vungle",
    "version": "6.9.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vqv4bg6xozeu5oflz5aopkgtbm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.vungle",
          "module": "publisher-sdk-android",
          "version": {
            "requires": "6.9.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "vungle-adapter",
          "version": {
            "requires": "6.9.1.a25"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "vungle",
          "version": {
            "requires": "6.9.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-vungle-6.9.1.2.aar",
          "url": "hera-vungle-6.9.1.2.aar",
          "size": 16551,
          "sha512": "669f4e68294c1ea075b9edbf11969de81934f6402ff85beafdadb1ab29293d3f112d9e98a015ccffc2f42a232de769f9a5d5393d418d2f67c9f1b14910be662c",
          "sha256": "d338ceaf690bc6d1301ad5f76d0405190e2824a50caebd1422721487fd0dba4e",
          "sha1": "27c3b0f5281373d65803c1990cec680da911c3df",
          "md5": "d60701c5c52fd83da07a4f1a6b89a344"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.vungle",
          "module": "publisher-sdk-android",
          "version": {
            "requires": "6.9.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "vungle-adapter",
          "version": {
            "requires": "6.9.1.a25"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "vungle",
          "version": {
            "requires": "6.9.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-vungle-6.9.1.2.aar",
          "url": "hera-vungle-6.9.1.2.aar",
          "size": 16551,
          "sha512": "669f4e68294c1ea075b9edbf11969de81934f6402ff85beafdadb1ab29293d3f112d9e98a015ccffc2f42a232de769f9a5d5393d418d2f67c9f1b14910be662c",
          "sha256": "d338ceaf690bc6d1301ad5f76d0405190e2824a50caebd1422721487fd0dba4e",
          "sha1": "27c3b0f5281373d65803c1990cec680da911c3df",
          "md5": "d60701c5c52fd83da07a4f1a6b89a344"
        }
      ]
    }
  ]
}
