{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-chartboost",
    "version": "8.2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "pnigqwdelnduzimyrigzahoowe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "chartboost",
          "version": {
            "requires": "8.2.0.a23"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "chartboost",
          "version": {
            "requires": "8.2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-chartboost-8.2.0.0.aar",
          "url": "hera-chartboost-8.2.0.0.aar",
          "size": 16307,
          "sha512": "950bc7528ef0668b49e033d5bd3ddeacb06b6fdc4cb6183b9f6e7be9a8f0e5a73c21b97df42d7ec9c8c6bf70348959dfcd412d9936a7e9c7bb86acfd51bf90d3",
          "sha256": "57c6c6047210512fb2b24f710645154b9f70e9c907ee85aad9d2ca55b6503874",
          "sha1": "5f53bcefa8c980a3ec2031eb8acb4a6ed9a098f2",
          "md5": "fb8634d4bed65851e32c41a0b82d6b21"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "chartboost",
          "version": {
            "requires": "8.2.0.a23"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "chartboost",
          "version": {
            "requires": "8.2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-chartboost-8.2.0.0.aar",
          "url": "hera-chartboost-8.2.0.0.aar",
          "size": 16307,
          "sha512": "950bc7528ef0668b49e033d5bd3ddeacb06b6fdc4cb6183b9f6e7be9a8f0e5a73c21b97df42d7ec9c8c6bf70348959dfcd412d9936a7e9c7bb86acfd51bf90d3",
          "sha256": "57c6c6047210512fb2b24f710645154b9f70e9c907ee85aad9d2ca55b6503874",
          "sha1": "5f53bcefa8c980a3ec2031eb8acb4a6ed9a098f2",
          "md5": "fb8634d4bed65851e32c41a0b82d6b21"
        }
      ]
    }
  ]
}
