{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-vungle",
    "version": "6.9.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qup4nywskba6zm7vkfs55m6wc4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.vungle",
          "module": "publisher-sdk-android",
          "version": {
            "requires": "6.9.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "vungle-adapter",
          "version": {
            "requires": "6.9.1.1.a25"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "vungle",
          "version": {
            "requires": "6.9.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "hera-vungle-6.9.1.3.aar",
          "url": "hera-vungle-6.9.1.3.aar",
          "size": 16616,
          "sha512": "d0dfe74ba098e3e66a580ba0d7d52b0e730678414c5d81ffc112e352100e3b476344bb0a0f385ee8591abf3a898c5e56c2106387fa62a387dddb849a87d8ee69",
          "sha256": "dea9fedb5869f50febc17f6b3499316bb5e4836ba8bc5a5ce44f9d6b4a0f390b",
          "sha1": "55aed1003867c305fd42903d8276f3bf96362d0f",
          "md5": "810ace05f3460c77b087b46fb1b10aa2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.vungle",
          "module": "publisher-sdk-android",
          "version": {
            "requires": "6.9.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "vungle-adapter",
          "version": {
            "requires": "6.9.1.1.a25"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "vungle",
          "version": {
            "requires": "6.9.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "hera-vungle-6.9.1.3.aar",
          "url": "hera-vungle-6.9.1.3.aar",
          "size": 16616,
          "sha512": "d0dfe74ba098e3e66a580ba0d7d52b0e730678414c5d81ffc112e352100e3b476344bb0a0f385ee8591abf3a898c5e56c2106387fa62a387dddb849a87d8ee69",
          "sha256": "dea9fedb5869f50febc17f6b3499316bb5e4836ba8bc5a5ce44f9d6b4a0f390b",
          "sha1": "55aed1003867c305fd42903d8276f3bf96362d0f",
          "md5": "810ace05f3460c77b087b46fb1b10aa2"
        }
      ]
    }
  ]
}
