{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ydf4jhe6cbagpcwbpu6635s7vq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "amr",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admost",
          "version": {
            "requires": "0.2.4.a25"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admob-gt-17.2.0-adapter",
          "version": {
            "requires": "1.0.6.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "facebook",
          "version": {
            "requires": "6.4.0.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "s2sbidding-adapter",
          "version": {
            "requires": "1.0.1.a25"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "hera-1.1.4.aar",
          "url": "hera-1.1.4.aar",
          "size": 128042,
          "sha512": "61ee9e3afbf31ba58f81907db964ba36d013002378c194ea849cbc87dde58c083768ede3c14a53edd5ecdf3a958e63cd0b4bdab9906ca72518427830669579b7",
          "sha256": "5e695053d81ddf0956924ce36d0e34e1dbb7542b055de0d5e764fb2c837544d4",
          "sha1": "70fcee9d5ae48292e430afd2bcf14c11a0e44251",
          "md5": "f6339a8cef18ae44cd33bb21c5fbddbd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "amr",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admost",
          "version": {
            "requires": "0.2.4.a25"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admob-gt-17.2.0-adapter",
          "version": {
            "requires": "1.0.6.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "facebook",
          "version": {
            "requires": "6.4.0.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "s2sbidding-adapter",
          "version": {
            "requires": "1.0.1.a25"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.mopub",
          "module": "mopub-sdk",
          "version": {
            "requires": "5.15.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mopub-sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "admob",
          "version": {
            "requires": "19.6.0.1"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "facebookaudiencenetwork",
          "version": {
            "requires": "6.3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-1.1.4.aar",
          "url": "hera-1.1.4.aar",
          "size": 128042,
          "sha512": "61ee9e3afbf31ba58f81907db964ba36d013002378c194ea849cbc87dde58c083768ede3c14a53edd5ecdf3a958e63cd0b4bdab9906ca72518427830669579b7",
          "sha256": "5e695053d81ddf0956924ce36d0e34e1dbb7542b055de0d5e764fb2c837544d4",
          "sha1": "70fcee9d5ae48292e430afd2bcf14c11a0e44251",
          "md5": "f6339a8cef18ae44cd33bb21c5fbddbd"
        }
      ]
    }
  ]
}
