{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vqv4bg6xozeu5oflz5aopkgtbm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "amr",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admost",
          "version": {
            "requires": "0.2.4.a25"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admob-gt-17.2.0-adapter",
          "version": {
            "requires": "1.0.6.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "facebook",
          "version": {
            "requires": "6.4.0.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "s2sbidding-adapter",
          "version": {
            "requires": "1.0.1.a25"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-1.1.0.aar",
          "url": "hera-1.1.0.aar",
          "size": 122935,
          "sha512": "65c80bab5c7f4ad2c7f7347735302acb4bdc1016a80eee5addb9ba82ef22ac115a5f99e0650a5942131f1c99a6d98957ff63ac2465e389fe8dae005b16186439",
          "sha256": "72ece8e9d8dc8fe00dfe5110aea1460f32dae4829878941b5cc017d7538e1104",
          "sha1": "b71a5fdd2a66332cdf5dab3df0fb3f2fa8015372",
          "md5": "a640cea3914199785d17bc5b83bc43d1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "amr",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admost",
          "version": {
            "requires": "0.2.4.a25"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "admob-gt-17.2.0-adapter",
          "version": {
            "requires": "1.0.6.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "facebook",
          "version": {
            "requires": "6.4.0.a25"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "s2sbidding-adapter",
          "version": {
            "requires": "1.0.1.a25"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.mopub",
          "module": "mopub-sdk",
          "version": {
            "requires": "5.15.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mopub-sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "admob",
          "version": {
            "requires": "19.6.0.1"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "facebookaudiencenetwork",
          "version": {
            "requires": "6.3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-1.1.0.aar",
          "url": "hera-1.1.0.aar",
          "size": 122935,
          "sha512": "65c80bab5c7f4ad2c7f7347735302acb4bdc1016a80eee5addb9ba82ef22ac115a5f99e0650a5942131f1c99a6d98957ff63ac2465e389fe8dae005b16186439",
          "sha256": "72ece8e9d8dc8fe00dfe5110aea1460f32dae4829878941b5cc017d7538e1104",
          "sha1": "b71a5fdd2a66332cdf5dab3df0fb3f2fa8015372",
          "md5": "a640cea3914199785d17bc5b83bc43d1"
        }
      ]
    }
  ]
}
