{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-chartboost",
    "version": "8.2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "sv2fum4h65hvnkyv7yjfdbsgmi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "chartboost",
          "version": {
            "requires": "8.2.0.1.a24"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "chartboost",
          "version": {
            "requires": "8.2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-chartboost-8.2.0.2.aar",
          "url": "hera-chartboost-8.2.0.2.aar",
          "size": 16612,
          "sha512": "95807711140956436aa9780bace1939d7a6617aed8198860c303f81015d3082ebd64534046232e0f4977d50a596e41a2035c6527c25d0c459a75e8a2d8c3de3a",
          "sha256": "48aa0a969851f9ac27990cce3f3efc096a34491ab27eb3f11ab095664fd3d3ae",
          "sha1": "0fb0eb44478e68a91468d6ab5a58e757cf1ea431",
          "md5": "5accb21a1d60d457becf17fd1429670f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "chartboost",
          "version": {
            "requires": "8.2.0.1.a24"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "chartboost",
          "version": {
            "requires": "8.2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-chartboost-8.2.0.2.aar",
          "url": "hera-chartboost-8.2.0.2.aar",
          "size": 16612,
          "sha512": "95807711140956436aa9780bace1939d7a6617aed8198860c303f81015d3082ebd64534046232e0f4977d50a596e41a2035c6527c25d0c459a75e8a2d8c3de3a",
          "sha256": "48aa0a969851f9ac27990cce3f3efc096a34491ab27eb3f11ab095664fd3d3ae",
          "sha1": "0fb0eb44478e68a91468d6ab5a58e757cf1ea431",
          "md5": "5accb21a1d60d457becf17fd1429670f"
        }
      ]
    }
  ]
}
