{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-vungle",
    "version": "6.8.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "pnigqwdelnduzimyrigzahoowe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.vungle",
          "module": "publisher-sdk-android",
          "version": {
            "requires": "6.8.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "vungle-adapter",
          "version": {
            "requires": "6.8.1.a23"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "vungle",
          "version": {
            "requires": "6.9.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-vungle-6.8.1.0.aar",
          "url": "hera-vungle-6.8.1.0.aar",
          "size": 16242,
          "sha512": "ed69ea342bfbb0c6acdf1a0c5d40fcff307d215497d98f8312e4f8d524333fc523f497f19ae00acf8d028042e659797bbd547c1971497628ce945546e183de01",
          "sha256": "da88f3471d01200e5ac4dcbcc91d17af32ced2d01226919c978265520850dbe3",
          "sha1": "18b76aa474019e3be3c10e21e9ee0579e4b1fb3e",
          "md5": "404cef8621b5ef0d55f9bbc32204da87"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.vungle",
          "module": "publisher-sdk-android",
          "version": {
            "requires": "6.8.1"
          }
        },
        {
          "group": "com.admost.sdk",
          "module": "vungle-adapter",
          "version": {
            "requires": "6.8.1.a23"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "vungle",
          "version": {
            "requires": "6.9.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-vungle-6.8.1.0.aar",
          "url": "hera-vungle-6.8.1.0.aar",
          "size": 16242,
          "sha512": "ed69ea342bfbb0c6acdf1a0c5d40fcff307d215497d98f8312e4f8d524333fc523f497f19ae00acf8d028042e659797bbd547c1971497628ce945546e183de01",
          "sha256": "da88f3471d01200e5ac4dcbcc91d17af32ced2d01226919c978265520850dbe3",
          "sha1": "18b76aa474019e3be3c10e21e9ee0579e4b1fb3e",
          "md5": "404cef8621b5ef0d55f9bbc32204da87"
        }
      ]
    }
  ]
}
