{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-unityads",
    "version": "3.7.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vqv4bg6xozeu5oflz5aopkgtbm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "unity",
          "version": {
            "requires": "3.7.1.a25"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "unityads",
          "version": {
            "requires": "3.7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-unityads-3.7.1.0.aar",
          "url": "hera-unityads-3.7.1.0.aar",
          "size": 16532,
          "sha512": "d47084c6cf710cd9dd1f023b614bbf1db619dc3d699f79b4659c5beec721ac575c8358dfeb61a3aeb2ec99dbb33a9e0c11932a3a96e3e1e8292b50e79564f326",
          "sha256": "9de88e14dbe261245d9a8ff101c0ea809b4aa6b5a6b6ed59d54d43c048a1d4ae",
          "sha1": "27853bd5302adabe96e949c765bd5a50797c439f",
          "md5": "a7d27c9883089ff61a53dc10b2b9ecd7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "unity",
          "version": {
            "requires": "3.7.1.a25"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "unityads",
          "version": {
            "requires": "3.7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-unityads-3.7.1.0.aar",
          "url": "hera-unityads-3.7.1.0.aar",
          "size": 16532,
          "sha512": "d47084c6cf710cd9dd1f023b614bbf1db619dc3d699f79b4659c5beec721ac575c8358dfeb61a3aeb2ec99dbb33a9e0c11932a3a96e3e1e8292b50e79564f326",
          "sha256": "9de88e14dbe261245d9a8ff101c0ea809b4aa6b5a6b6ed59d54d43c048a1d4ae",
          "sha1": "27853bd5302adabe96e949c765bd5a50797c439f",
          "md5": "a7d27c9883089ff61a53dc10b2b9ecd7"
        }
      ]
    }
  ]
}
