{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-unityads",
    "version": "3.6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "pnigqwdelnduzimyrigzahoowe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "unity",
          "version": {
            "requires": "3.6.0.1.a23"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "unityads",
          "version": {
            "requires": "3.6.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-unityads-3.6.0.0.aar",
          "url": "hera-unityads-3.6.0.0.aar",
          "size": 16220,
          "sha512": "5f34ebdee11b1fb65bcd1ce45b84b100d0dc3bda104df8c45c3fc5fdea0a82812db32db20a261a003ed3e1e2938fff0242bd728ef90a9ce5b0e15eb1d6fe91e7",
          "sha256": "3d5a0c51d9491299980745a72256521ba6651c2d567513e41d324d65f697d5e5",
          "sha1": "260ecc4afedcda9377cacad15d55e421420a16ce",
          "md5": "abbda02f74623977b9b23c6b2f4134d3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "unity",
          "version": {
            "requires": "3.6.0.1.a23"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "unityads",
          "version": {
            "requires": "3.6.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-unityads-3.6.0.0.aar",
          "url": "hera-unityads-3.6.0.0.aar",
          "size": 16220,
          "sha512": "5f34ebdee11b1fb65bcd1ce45b84b100d0dc3bda104df8c45c3fc5fdea0a82812db32db20a261a003ed3e1e2938fff0242bd728ef90a9ce5b0e15eb1d6fe91e7",
          "sha256": "3d5a0c51d9491299980745a72256521ba6651c2d567513e41d324d65f697d5e5",
          "sha1": "260ecc4afedcda9377cacad15d55e421420a16ce",
          "md5": "abbda02f74623977b9b23c6b2f4134d3"
        }
      ]
    }
  ]
}
