{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-ironsource",
    "version": "7.1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "pnigqwdelnduzimyrigzahoowe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "ironsource",
          "version": {
            "requires": "7.1.0.1.a23"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "ironsource",
          "version": {
            "requires": "7.1.0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-ironsource-7.1.0.0.aar",
          "url": "hera-ironsource-7.1.0.0.aar",
          "size": 16248,
          "sha512": "efb243bd0e35c71d1a7e8b90c5b2f933d49b3c0d228db23028a42cdb01b644973690eaaf9d86f172dddbead6502ab4875b36295ca3091c49996d33fcf38ee295",
          "sha256": "afd2ab5c5f763d4e905d570b9247b9bc31d67acf26263fdac25170db1323753c",
          "sha1": "cd50d7fb0dd9e243586fcda1b76f904fac9ad94b",
          "md5": "a3fefea106ee1c75e8dc697050ed846c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "ironsource",
          "version": {
            "requires": "7.1.0.1.a23"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "ironsource",
          "version": {
            "requires": "7.1.0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "hera-ironsource-7.1.0.0.aar",
          "url": "hera-ironsource-7.1.0.0.aar",
          "size": 16248,
          "sha512": "efb243bd0e35c71d1a7e8b90c5b2f933d49b3c0d228db23028a42cdb01b644973690eaaf9d86f172dddbead6502ab4875b36295ca3091c49996d33fcf38ee295",
          "sha256": "afd2ab5c5f763d4e905d570b9247b9bc31d67acf26263fdac25170db1323753c",
          "sha1": "cd50d7fb0dd9e243586fcda1b76f904fac9ad94b",
          "md5": "a3fefea106ee1c75e8dc697050ed846c"
        }
      ]
    }
  ]
}
