{
  "formatVersion": "1.1",
  "component": {
    "group": "hera",
    "module": "hera-ironsource",
    "version": "7.1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vqv4bg6xozeu5oflz5aopkgtbm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "ironsource",
          "version": {
            "requires": "7.1.5.1.a25"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "ironsource",
          "version": {
            "requires": "7.1.5.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-ironsource-7.1.5.0.aar",
          "url": "hera-ironsource-7.1.5.0.aar",
          "size": 16562,
          "sha512": "6da5e75437ed1e5ba486af621503ef81b2832c3251c05a5cca8d53fbf2b0a15fa55d30fa7bd67d16a1923d403d1caf3d0bf852c91d3bec0bb6303c598b450b84",
          "sha256": "c1cfed21697abc3709ee1b7cc55cfb876aaee3d29e0dd8a11326cee1a231ed8d",
          "sha1": "4fa3f18a973f002d76451b31cefcf4ea4d22183c",
          "md5": "a71eb22d42a18773fa49e327654a3c4b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.admost.sdk",
          "module": "ironsource",
          "version": {
            "requires": "7.1.5.1.a25"
          }
        },
        {
          "group": "com.mopub.mediation",
          "module": "ironsource",
          "version": {
            "requires": "7.1.5.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "hera-ironsource-7.1.5.0.aar",
          "url": "hera-ironsource-7.1.5.0.aar",
          "size": 16562,
          "sha512": "6da5e75437ed1e5ba486af621503ef81b2832c3251c05a5cca8d53fbf2b0a15fa55d30fa7bd67d16a1923d403d1caf3d0bf852c91d3bec0bb6303c598b450b84",
          "sha256": "c1cfed21697abc3709ee1b7cc55cfb876aaee3d29e0dd8a11326cee1a231ed8d",
          "sha1": "4fa3f18a973f002d76451b31cefcf4ea4d22183c",
          "md5": "a71eb22d42a18773fa49e327654a3c4b"
        }
      ]
    }
  ]
}
